name: Compile and Test

on: [push]

env:
  CI: true # disables SBT super shell which has problems with CI environments

jobs:
  compile-lib:
    name: Compile library
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        scala: [2.11.12, 2.12.14, 2.13.6]
        platform: [JVM, JS, Native]

    env:
      SCALA_VERSION: ${{ matrix.scala }}
      PROJECT: root${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Compile (Scala ${{ matrix.scala }} - ${{ matrix.platform }})
      run: sbt -Dsbt.color=always ++$SCALA_VERSION $PROJECT/compile
  compile-examples:
    name: Compile examples
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        scala: [2.11.12, 2.12.14, 2.13.6]

    env:
      SCALA_VERSION: ${{ matrix.scala }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Compile examples (Scala ${{ matrix.scala }})
      run: sbt -Dsbt.color=always ++$SCALA_VERSION examples/compile
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        scala: [2.11.12, 2.12.14, 2.13.6]
        platform: [JVM, JS, Native]

    env:
      SCALA_VERSION: ${{ matrix.scala }}
      PROJECT: root${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Install scala-native libraries
      run: sudo apt-get update && sudo apt-get -y install libunwind-dev libre2-dev libsdl2-dev
    - name: Run tests (Scala ${{ matrix.scala }} - ${{ matrix.platform }})
      run: sbt -Dsbt.color=always ++$SCALA_VERSION $PROJECT/test:compile $PROJECT/test
