name: Compile and Test

on: [push]

env:
  CI: true # disables SBT super shell which has problems with CI environments

jobs:
  build:
    name: Scala ${{ matrix.scala }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        scala: [2.11.12, 2.12.10, 2.13.1]

    env:
      SCALA_VERSION: ${{ matrix.scala }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: openjdk@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Compile
      run: sbt -Dsbt.color=always ++$SCALA_VERSION compile
    - name: Run tests
      run: sbt -Dsbt.color=always ++$SCALA_VERSION test:compile test
