name: Compile and Test

on: [push, pull_request]

env:
  CI: true # disables SBT super shell which has problems with CI environments

jobs:
  compile-lib:
    name: Compile library
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        scala: [2.11.12, 2.12.16, 2.13.8, 3.1.3]

    env:
      SCALA_VERSION: ${{ matrix.scala }}
      PROJECT: root${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v13
      with:
        java-version: adopt@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Compile (Scala ${{ matrix.scala }} - ${{ matrix.platform }})
      run: sbt -Dsbt.color=always ++$SCALA_VERSION $PROJECT/compile
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        scala: [2.11.12, 2.12.16, 2.13.8, 3.1.3]
        platform: [JVM, JS, Native]

    env:
      SCALA_VERSION: ${{ matrix.scala }}
      PROJECT: root${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v13
      with:
        java-version: adopt@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Install scala-native libraries
      run: sudo apt-get update && sudo apt-get -y install libunwind-dev libre2-dev libsdl2-dev
    - name: Run tests (Scala ${{ matrix.scala }} - ${{ matrix.platform }})
      run: sbt -Dsbt.color=always ++$SCALA_VERSION $PROJECT/test:compile $PROJECT/test
  compile-examples:
    name: Compile examples
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v13
      with:
        java-version: adopt@1.8
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Install Scala-CLI
      run: |
        curl -fL https://github.com/Virtuslab/scala-cli/releases/latest/download/scala-cli-x86_64-pc-linux.gz | gzip -d > scala-cli
        chmod +x scala-cli
        sudo mv scala-cli /usr/local/bin/scala-cli
    - name: Compile examples (Release)
      run: |
        cd examples/release
        ls | grep .sc | xargs scala-cli compile
    - name: Publish Local
      run: sbt -Dsbt.color=always publishLocal
    - name: Compile examples (Snapshot)
      run: |
        cd examples/snapshot
        ls | grep .sc | xargs scala-cli compile
